route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]


receivers:
  - name: telegram
    webhook_configs:
    - send_resolved: true
      url: http://127.0.0.1:9087/alert/-chat_id
