version: '3.3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.25.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
        - ./alertmanager.yml:/etc/alertmanager/config.yml
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  graphana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
